<?xml version='1.0'?>

<robot name="myrobot" xmlns:xacro="http://www.ros.org/wiki/xacro">


  <xacro:include filename="$(find mini_jaguar_pkg)/gazebo_plugin/lidar.gazebo" />


  <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${chassis_L/2 + lidar_x} ${lidar_y} ${off_The_Ground + chassis_H + lidar_z}" rpy="0 0 0"/>
    <parent link="${link_00_name}"/>
    <child link="hokuyo"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="hokuyo">
     <collision>
      <origin xyz="0 0 -.03" rpy="1.57 0 0"/>
      <geometry>
     <mesh filename="package://mini_jaguar_pkg/meshes/rplidar.dae" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 -0.03" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://mini_jaguar_pkg/meshes/rplidar.dae" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
</robot>

