<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- <xacro:property name="wheels_mass" value="2" /> -->
           
        
   <m_joint name="${link_00_name}__${link_02_name}" type="continuous"
           axis_xyz="0 1 0"
           origin_rpy="0 0 0" origin_xyz="${chassis_L/2 - wheel_R} ${ chassis_W/2 + wheel_L/2 + wheels_offset } ${chassis_H/2 + off_The_Ground}"
           parent="${link_00_name}" child="${link_02_name}"
           limit_e="1000" limit_l="-3.14" limit_u="3.14" limit_v="0.5" />
         
  <m_link_mesh name="${link_02_name}"
              origin_rpy="0 0 0" origin_xyz="0 0 0"
              mass="${wheels_mass}"
              ixx=".1" ixy="0.0" ixz="0.0"
              iyy=".1" iyz="0.0"
              izz=".1"
              meshfile="package://mini_jaguar_pkg/meshes/tyre.dae"
              meshscale="1.7 1.7 1.7" /> 

    <m_joint name="${link_00_name}__${link_03_name}" type="continuous"
           axis_xyz="0 1 0"
           origin_rpy="0 0 0" origin_xyz="${chassis_L/2 - wheel_R} ${-(chassis_W/2 + wheel_L/2 + wheels_offset)} ${chassis_H/2 + off_The_Ground }"
           parent="${link_00_name}" child="${link_03_name}"
           limit_e="1000" limit_l="-3.14" limit_u="3.14" limit_v="0.5" />
           
  <m_link_mesh name="${link_03_name}"
              origin_rpy="0 0 0" origin_xyz="0 0 0"
              mass="${wheels_mass}"
              ixx=".1" ixy="0.0" ixz="0.0"
              iyy=".1" iyz="0.0"
              izz=".1" 
              meshfile="package://mini_jaguar_pkg/meshes/tyre.dae"
              meshscale="1.7 1.7 1.7" /> 

    <m_joint name="${link_00_name}__${link_04_name}" type="continuous"
           axis_xyz="0 1 0"
           origin_rpy="0 0 0" origin_xyz="${-(chassis_L/2 - wheel_R)} ${-(chassis_W/2 + wheel_L/2 + wheels_offset)} ${chassis_H/2 + off_The_Ground }"
           parent="${link_00_name}" child="${link_04_name}"
           limit_e="1000" limit_l="-3.14" limit_u="3.14" limit_v="0.5" />
           
  <m_link_mesh name="${link_04_name}"
              origin_rpy="0 0 0" origin_xyz="0 0 0"
              mass="${wheels_mass}"
              ixx=".1" ixy="0.0" ixz="0.0"
              iyy=".1" iyz="0.0"
              izz=".1"
              meshfile="package://mini_jaguar_pkg/meshes/tyre.dae"
              meshscale="1.7 1.7 1.7" /> 

      <m_joint name="${link_00_name}__${link_05_name}" type="continuous"
           axis_xyz="0 1 0"
           origin_rpy="0 0 0" origin_xyz="${-(chassis_L/2 - wheel_R)} ${(chassis_W/2 + wheel_L/2 + wheels_offset)} ${chassis_H/2 + off_The_Ground }"
           parent="${link_00_name}" child="${link_05_name}"
           limit_e="1000" limit_l="-3.14" limit_u="3.14" limit_v="0.5" />
           
  <m_link_mesh name="${link_05_name}" 
              origin_rpy="0 0 0" origin_xyz="0 0 0"
              mass="${wheels_mass}"
              ixx=".1" ixy="0.0" ixz="0.0"
              iyy=".1" iyz="0.0"
              izz=".1"
              meshfile="package://mini_jaguar_pkg/meshes/tyre.dae"
              meshscale="1.7 1.7 1.7" /> 
  
</robot>
