jaguar_arm_controller:
  # Position Controllers ---------------------------------------
  base_position_controller:
    type: position_controllers/JointPositionController
    joint: chassis__base_arm
  arm_1_position_controller:
    type: position_controllers/JointPositionController
    joint: base_arm__arm_1
  arm_2_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_1__arm_2
  arm_3_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_2__arm_3
  arm_4_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_3__arm_4

gazebo_ros_control/pid_gains:
  chassis__base_arm: {p: 100.0, i: 0.01, d: 10.0}
  base_arm__arm_1:   {p: 100.0, i: 0.01, d: 10.0}
  arm_1__arm_2:      {p: 100.0, i: 0.01, d: 10.0}
  arm_2__arm_3:      {p: 100.0, i: 0.01, d: 10.0}
  arm_3__arm_4:      {p: 100.0, i: 0.01, d: 10.0}
  # link_09__link_10: {p: 100.0, i: 0.01, d: 10.0}
  # link_09__link_11: {p: 100.0, i: 0.01, d: 10.0}