<?xml version="1.0"?>
<robot name="jaguar" xmlns:xacro="http://ros.org/wiki/xacro">
 
 
 <xacro:property name="M_PI" value="3.14159265358979323846264338327950288" />
 
 <xacro:include filename="$(find jaguar_pkg)/lib/_d435.urdf.xacro" />


  <sensor_d435 parent="${link_00_name}">
    <origin xyz="${chassis_L/2 + kinect_x} ${kinect_y} ${(wheel_R + chassis_H/2 + kinect_z) }" rpy="0 0 0"/>
  </sensor_d435>


<xacro:property name="name" value="camera" />
 
  <gazebo reference="camera_link">
    <sensor type="depth" name="${name}_frame_sensor">
      <always_on>true</always_on>
      <update_rate>20.0</update_rate>
      <camera>
        <horizontal_fov>${57.0*M_PI/180.0}</horizontal_fov>
        <image>
          <format>R8G8B8</format>
          <width>640</width>
          <height>480</height>
        </image>
        <clip>
          <near>0.01</near>
          <far>5</far>
        </clip>
      </camera>
      <plugin name="${name}_frame_controller" filename="libgazebo_ros_openni_kinect.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>20.0</updateRate>
        <cameraName>${name}</cameraName>
        <imageTopicName>${name}/ir/image_raw</imageTopicName>
        <cameraInfoTopicName>${name}/ir/camera_info</cameraInfoTopicName>
        <depthImageTopicName>${name}/depth/image_raw</depthImageTopicName>
        <depthImageCameraInfoTopicName>${name}/depth/camera_info</depthImageCameraInfoTopicName>
        <pointCloudTopicName>${name}/depth/points</pointCloudTopicName>
        <frameName>camera_depth_optical_frame</frameName>
        <pointCloudCutoff>0.5</pointCloudCutoff>
        <distortionK1>0.00000001</distortionK1>
        <distortionK2>0.00000001</distortionK2>
        <distortionK3>0.00000001</distortionK3>
        <distortionT1>0.00000001</distortionT1>
        <distortionT2>0.00000001</distortionT2>
        <CxPrime>0</CxPrime>
        <Cx>0</Cx>
        <Cy>0</Cy>
        <focalLength>0</focalLength>
        <hackBaseline>0</hackBaseline>
      </plugin>
    </sensor>
  </gazebo>
</robot>
