<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  
   <xacro:property name="_x" value="${chassis_L/2 - wheel_R}" /> 


<!-- Front Left -->
  <m_joint name="${link_00_name}__${link_12_name}" type="continuous"
           axis_xyz="0 1 0"
           origin_rpy="0 2.97 3.14" origin_xyz="${_x} ${ chassis_W/2 + wheel_L + fin_w + wheels_offset*3 }  ${wheel_R}"
           parent="${link_00_name}" child="${link_12_name}"
           limit_e="1000" limit_l="-1.57" limit_u="1.57" limit_v="0.5" />

  <m_link_mesh name="${link_12_name}"
              origin_rpy="0 0 0" origin_xyz="0  0 0"
              mass="${fins_mass}"
              ixx="0.1" ixy="0" ixz="0"
              iyy="0.1" iyz="0"
              izz="0.1"
              meshfile="${the_meshfile}/flipper.dae"
              meshscale="${fin_scale_x} ${fin_scale_y} ${fin_scale_z}" /> 

<!-- Rear Left -->
   <m_joint name="${link_00_name}__${link_13_name}" type="continuous"
           axis_xyz="0 1 0"
           origin_rpy="0 0 0" origin_xyz="${- _x} ${ chassis_W/2 + wheel_L + fin_w + wheels_offset*3 }  ${wheel_R}"
           parent="${link_00_name}" child="${link_13_name}"
           limit_e="1000" limit_l="-1.57" limit_u="1.57" limit_v="0.5" />

  <m_link_mesh name="${link_13_name}"
              origin_rpy="0 0 3.14" origin_xyz="0 0 0"
              mass="${fins_mass}"
              ixx="0.1" ixy="0" ixz="0"
              iyy="0.1" iyz="0"
              izz="0.1"
              meshfile="${the_meshfile}/flipper.dae"
              meshscale="${fin_scale_x} ${fin_scale_y} ${fin_scale_z}" /> 

<!-- Front Right -->
   <m_joint name="${link_00_name}__${link_14_name}" type="continuous"
           axis_xyz="0 1 0"
           origin_rpy="0 -0.17 3.14" origin_xyz="${_x} ${ -(chassis_W/2 + wheel_L + fin_w + wheels_offset*3) }  ${wheel_R}"
           parent="${link_00_name}" child="${link_14_name}"
           limit_e="1000" limit_l="-1.57" limit_u="1.57" limit_v="0.5" />

  <m_link_mesh name="${link_14_name}"
              origin_rpy="0 0 3.14" origin_xyz="0 0 0"
              mass="${fins_mass}"
              ixx="0.1" ixy="0" ixz="0"
              iyy="0.1" iyz="0"
              izz="0.1"
              meshfile="${the_meshfile}/flipper.dae"
              meshscale="${fin_scale_x} ${fin_scale_y} ${fin_scale_z}" /> 

<!-- Rear right -->
  <m_joint name="${link_00_name}__${link_15_name}" type="continuous"
           axis_xyz="0 1 0"
           origin_rpy="0 0 0" origin_xyz="${- _x} ${-(chassis_W/2 + wheel_L + fin_w + wheels_offset*3)}  ${wheel_R}"
           parent="${link_00_name}" child="${link_15_name}"
           limit_e="1000" limit_l="-1.57" limit_u="1.57" limit_v="0.5" />

  <m_link_mesh name="${link_15_name}"
              origin_rpy="0 3.14 0" origin_xyz="0 0 0"
              mass="${fins_mass}"
              ixx="0.1" ixy="0" ixz="0"
              iyy="0.1" iyz="0"
              izz="0.1"
              meshfile="${the_meshfile}/flipper.dae"
              meshscale="${fin_scale_x} ${fin_scale_y} ${fin_scale_z}" />    
</robot>