obstacle_range: 2.5  #2.5
raytrace_range: 1.0   #3.0
footprint: [[-0.18, -0.13], [-0.18, 0.13], [0.18, 0.13], [0.18, -0.13]]
# footprint: [[-0.43, -0.25], [-0.43, 0.25], [0.35, 0.25], [0.35, -0.25]]
#robot_radius: ir_of_robot
robot_radius: 0.5 # distance a circular robot should be clear of the obstacle
footprint_padding: 0.01
inflation_radius: 0.15 # distance a circular obstacle (walls ..) should be clear. 

#observation_sources: point_cloud_sensor 
observation_sources: laser_scan_sensor 

# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /mybot/laser/scan, marking: true, clearing: true}

# point_cloud_sensor: {sensor_frame: velodyne, data_type: PointCloud, topic: /velodyne_points, marking: true, clearing: true}
