<?xml version="1.0" ?>

<robot name="mrmg" xmlns:xacro="http://www.ros.org/wiki/xacro">
   
  <!-- BGN - Include -->
  <xacro:include filename="$(find mini_jaguar_pkg)/urdf/robot_parameters.xacro" />
  <xacro:include filename="$(find mini_jaguar_pkg)/urdf/links_joints.xacro" />



   <xacro:include filename="$(find mini_jaguar_pkg)/parts/wheels.xacro" />
   <xacro:include filename="$(find mini_jaguar_pkg)/parts/lidar_2d.xacro" />
   <xacro:include filename="$(find mini_jaguar_pkg)/parts/velodyne.xacro" />
   <xacro:include filename="$(find mini_jaguar_pkg)/parts/arm.xacro" />
   <!-- <xacro:include filename="$(find mini_jaguar_pkg)/parts/fins.xacro" />  -->

  <xacro:include filename="$(find mini_jaguar_pkg)/urdf/mini.gazebo" />

  <!-- END - Include -->
  <link name="${dummy_link}">
  </link>

  <joint name="dummy_joint" type="fixed">
     <parent link="${dummy_link}"/>
     <child link="${link_00_name}"/>
  </joint>

  <link name='${link_00_name}'>
    <pose>0 0 0.1 0 0 0</pose>

    <inertial>
      <mass value="${chassis_mass}"/>
      <origin xyz="0 0 1" rpy=" 0 0 0"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>
    <collision name='collision'>
     <origin xyz="0 0 ${chassis_H/2 + off_The_Ground}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_L}  ${chassis_W}  ${chassis_H}"/>
      </geometry>
    </collision>

    <visual name='chassis_visual'>
      <origin xyz="0 0 ${chassis_H/2 + off_The_Ground}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${chassis_L}  ${chassis_W}  ${chassis_H}"/>
      </geometry>
    </visual>
  </link>


<link name='bar'>
    <pose>0 0 0.1 0 0 0</pose>

    <inertial>
      <mass value="${bar_mass}"/>
      <origin xyz="0 0 ${bar_H/2}" rpy=" 0 0 0"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>

    <collision name='collision'>
    <!-- <origin xyz="0 0 ${bar_H/2}" rpy="0 0 0"/> -->
      <geometry>
        <box size="${bar_L}  ${bar_W}  ${bar_H}"/>
      </geometry>
    </collision>

    <visual name='bar_visual'>
      <origin xyz="0 0 ${0}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${bar_L}  ${bar_W}  ${bar_H}"/>
      </geometry>
    </visual>
  </link>

  <joint name="bar_joint" type="fixed">
    <origin xyz="${-bar_x} ${bar_y} ${bar_H/2 + bar_z + off_The_Ground}" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="bar"/>
  </joint>       


</robot>
